// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261003052804_lan001")]
    partial class lan001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("BrandId");

                    b.HasIndex("BrandName")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Healthy Mart",
                            Country = "Việt Nam",
                            Description = "Thương hiệu riêng của cửa hàng",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Quaker",
                            Country = "Mỹ",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "TH true MILK",
                            Country = "Việt Nam",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Vinamilk",
                            Country = "Việt Nam",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "Alsafi",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 6,
                            BrandName = "Bertolli",
                            Country = "Ý",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 7,
                            BrandName = "Organic Farm VN",
                            Country = "Việt Nam",
                            Description = "Nông sản hữu cơ (dữ liệu mẫu)",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 8,
                            BrandName = "Eat Clean VN",
                            Country = "Việt Nam",
                            Description = "Thực phẩm ăn kiêng (dữ liệu mẫu)",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 9,
                            BrandName = "Dalat Green",
                            Country = "Việt Nam",
                            Description = "Trà thảo mộc (dữ liệu mẫu)",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 10,
                            BrandName = "Blue Diamond",
                            Country = "Mỹ",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 11,
                            BrandName = "Bee Gold",
                            Country = "Việt Nam",
                            Description = "Mật ong nguyên chất (dữ liệu mẫu)",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 12,
                            BrandName = "Nutri Seed",
                            Country = "Việt Nam",
                            Description = "Superfood (dữ liệu mẫu)",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Rau củ quả hữu cơ",
                            Description = "Rau xanh, củ quả tươi đạt chuẩn organic"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Ngũ cốc & Hạt dinh dưỡng",
                            Description = "Yến mạch, hạt chia, hạnh nhân, óc chó"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa hạt & Sữa chua hữu cơ",
                            Description = "Sữa hạnh nhân, sữa đậu nành, sữa chua Hy Lạp"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Thực phẩm Eat Clean",
                            Description = "Ức gà, cơm gạo lứt, salad đóng gói ăn kiêng"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu thực vật tự nhiên",
                            Description = "Dầu oliu, mật ong nguyên chất, muối hồng Himalaya"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Trái cây tươi & nhập khẩu",
                            Description = "Táo, nho, kiwi, bơ, trái cây theo mùa"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Thịt cá sạch",
                            Description = "Cá hồi, thịt bò, thịt heo, hải sản tươi đạt chuẩn"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Trứng & Chế phẩm từ trứng",
                            Description = "Trứng gà ta, trứng gà hữu cơ, trứng cút"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Trà & Đồ uống tốt cho sức khỏe",
                            Description = "Trà thảo mộc, nước ép nguyên chất, kombucha"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Bánh & Snack lành mạnh",
                            Description = "Bánh yến mạch, snack rong biển, trái cây sấy"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Đậu & Sản phẩm từ đậu",
                            Description = "Đậu hũ, tempeh, các loại đậu khô"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Superfood & Thực phẩm bổ sung",
                            Description = "Spirulina, matcha, bột rau củ, collagen thực vật"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "12 Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh",
                            CustomerName = "Phạm Minh Tuấn",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0905123456",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "45 Lê Lợi, Quận 3, TP. Hồ Chí Minh",
                            CustomerName = "Hoàng Thị Lan",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 75
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "8 Trần Hưng Đạo, Quận 5, TP. Hồ Chí Minh",
                            CustomerName = "Võ Quốc Bảo",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0937654321",
                            RewardPoints = 20
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "102 Điện Biên Phủ, Bình Thạnh, TP. Hồ Chí Minh",
                            CustomerName = "Đặng Thu Hà",
                            MembershipRank = "Kim cương",
                            PhoneNumber = "0944556677",
                            RewardPoints = 520
                        },
                        new
                        {
                            CustomerId = 8,
                            CustomerName = "Bùi Anh Khoa",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0966778899",
                            RewardPoints = 5
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "27 Phan Văn Trị, Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Ngô Thanh Mai",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0977889900",
                            RewardPoints = 90
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "63 Cách Mạng Tháng 8, Quận 10, TP. Hồ Chí Minh",
                            CustomerName = "Đỗ Hoài Nam",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0988990011",
                            RewardPoints = 210
                        },
                        new
                        {
                            CustomerId = 11,
                            CustomerName = "Lý Gia Hân",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0399123456",
                            RewardPoints = 0
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "5 Võ Văn Ngân, Thủ Đức, TP. Hồ Chí Minh",
                            CustomerName = "Trương Quốc Việt",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0868234567",
                            RewardPoints = 60
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CashierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CashierId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CashierId = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Discount = 0m,
                            OrderCode = "HD0001",
                            PaymentMethod = "CASH",
                            Status = "PAID",
                            Subtotal = 82000m,
                            Total = 82000m
                        },
                        new
                        {
                            OrderId = 2,
                            CashierId = 4,
                            CreatedAt = new DateTime(2026, 9, 2, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Discount = 10000m,
                            OrderCode = "HD0002",
                            PaymentMethod = "MOMO",
                            Status = "PAID",
                            Subtotal = 221000m,
                            Total = 211000m
                        },
                        new
                        {
                            OrderId = 3,
                            CashierId = 5,
                            CreatedAt = new DateTime(2026, 9, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0m,
                            OrderCode = "HD0003",
                            PaymentMethod = "CASH",
                            Status = "PAID",
                            Subtotal = 173000m,
                            Total = 173000m
                        },
                        new
                        {
                            OrderId = 4,
                            CashierId = 5,
                            CreatedAt = new DateTime(2026, 9, 4, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 7,
                            Discount = 20000m,
                            OrderCode = "HD0004",
                            PaymentMethod = "CARD",
                            Status = "PAID",
                            Subtotal = 400000m,
                            Total = 380000m
                        },
                        new
                        {
                            OrderId = 5,
                            CashierId = 6,
                            CreatedAt = new DateTime(2026, 9, 5, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            Discount = 23000m,
                            OrderCode = "HD0005",
                            PaymentMethod = "BANK_TRANSFER",
                            Status = "PAID",
                            Subtotal = 467000m,
                            Total = 444000m
                        },
                        new
                        {
                            OrderId = 6,
                            CashierId = 6,
                            CreatedAt = new DateTime(2026, 9, 6, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0m,
                            OrderCode = "HD0006",
                            PaymentMethod = "CASH",
                            Status = "PAID",
                            Subtotal = 158000m,
                            Total = 158000m
                        },
                        new
                        {
                            OrderId = 7,
                            CashierId = 7,
                            CreatedAt = new DateTime(2026, 9, 7, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Discount = 0m,
                            OrderCode = "HD0007",
                            PaymentMethod = "CASH",
                            Status = "PAID",
                            Subtotal = 126000m,
                            Total = 126000m
                        },
                        new
                        {
                            OrderId = 8,
                            CashierId = 7,
                            CreatedAt = new DateTime(2026, 9, 8, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 10,
                            Discount = 12000m,
                            OrderCode = "HD0008",
                            PaymentMethod = "MOMO",
                            Status = "PAID",
                            Subtotal = 237000m,
                            Total = 225000m
                        },
                        new
                        {
                            OrderId = 9,
                            CashierId = 8,
                            CreatedAt = new DateTime(2026, 9, 9, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            Discount = 0m,
                            OrderCode = "HD0009",
                            PaymentMethod = "CARD",
                            Status = "PAID",
                            Subtotal = 151000m,
                            Total = 151000m
                        },
                        new
                        {
                            OrderId = 10,
                            CashierId = 8,
                            CreatedAt = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0m,
                            OrderCode = "HD0010",
                            PaymentMethod = "CASH",
                            Status = "CANCELLED",
                            Subtotal = 129000m,
                            Total = 129000m
                        },
                        new
                        {
                            OrderId = 11,
                            CashierId = 9,
                            CreatedAt = new DateTime(2026, 9, 11, 15, 25, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 9,
                            Discount = 12000m,
                            OrderCode = "HD0011",
                            PaymentMethod = "BANK_TRANSFER",
                            Status = "PAID",
                            Subtotal = 262000m,
                            Total = 250000m
                        },
                        new
                        {
                            OrderId = 12,
                            CashierId = 9,
                            CreatedAt = new DateTime(2026, 9, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 12,
                            Discount = 0m,
                            OrderCode = "HD0012",
                            PaymentMethod = "MOMO",
                            Status = "PAID",
                            Subtotal = 258000m,
                            Total = 258000m
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            LineTotal = 50000m,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 25000m
                        },
                        new
                        {
                            OrderItemId = 2,
                            LineTotal = 32000m,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 32000m
                        },
                        new
                        {
                            OrderItemId = 3,
                            LineTotal = 65000m,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 65000m
                        },
                        new
                        {
                            OrderItemId = 4,
                            LineTotal = 156000m,
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 2,
                            UnitPrice = 78000m
                        },
                        new
                        {
                            OrderItemId = 5,
                            LineTotal = 89000m,
                            OrderId = 3,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 89000m
                        },
                        new
                        {
                            OrderItemId = 6,
                            LineTotal = 84000m,
                            OrderId = 3,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 42000m
                        },
                        new
                        {
                            OrderItemId = 7,
                            LineTotal = 145000m,
                            OrderId = 4,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 145000m
                        },
                        new
                        {
                            OrderItemId = 8,
                            LineTotal = 120000m,
                            OrderId = 4,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 120000m
                        },
                        new
                        {
                            OrderItemId = 9,
                            LineTotal = 135000m,
                            OrderId = 4,
                            ProductId = 17,
                            Quantity = 1,
                            UnitPrice = 135000m
                        },
                        new
                        {
                            OrderItemId = 10,
                            LineTotal = 338000m,
                            OrderId = 5,
                            ProductId = 12,
                            Quantity = 2,
                            UnitPrice = 169000m
                        },
                        new
                        {
                            OrderItemId = 11,
                            LineTotal = 129000m,
                            OrderId = 5,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 129000m
                        },
                        new
                        {
                            OrderItemId = 12,
                            LineTotal = 104000m,
                            OrderId = 6,
                            ProductId = 13,
                            Quantity = 2,
                            UnitPrice = 52000m
                        },
                        new
                        {
                            OrderItemId = 13,
                            LineTotal = 54000m,
                            OrderId = 6,
                            ProductId = 16,
                            Quantity = 3,
                            UnitPrice = 18000m
                        },
                        new
                        {
                            OrderItemId = 14,
                            LineTotal = 48000m,
                            OrderId = 7,
                            ProductId = 14,
                            Quantity = 1,
                            UnitPrice = 48000m
                        },
                        new
                        {
                            OrderItemId = 15,
                            LineTotal = 78000m,
                            OrderId = 7,
                            ProductId = 15,
                            Quantity = 2,
                            UnitPrice = 39000m
                        },
                        new
                        {
                            OrderItemId = 16,
                            LineTotal = 95000m,
                            OrderId = 8,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 95000m
                        },
                        new
                        {
                            OrderItemId = 17,
                            LineTotal = 110000m,
                            OrderId = 8,
                            ProductId = 6,
                            Quantity = 2,
                            UnitPrice = 55000m
                        },
                        new
                        {
                            OrderItemId = 18,
                            LineTotal = 32000m,
                            OrderId = 8,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 32000m
                        },
                        new
                        {
                            OrderItemId = 19,
                            LineTotal = 126000m,
                            OrderId = 9,
                            ProductId = 8,
                            Quantity = 3,
                            UnitPrice = 42000m
                        },
                        new
                        {
                            OrderItemId = 20,
                            LineTotal = 25000m,
                            OrderId = 9,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 25000m
                        },
                        new
                        {
                            OrderItemId = 21,
                            LineTotal = 129000m,
                            OrderId = 10,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 129000m
                        },
                        new
                        {
                            OrderItemId = 22,
                            LineTotal = 130000m,
                            OrderId = 11,
                            ProductId = 3,
                            Quantity = 2,
                            UnitPrice = 65000m
                        },
                        new
                        {
                            OrderItemId = 23,
                            LineTotal = 96000m,
                            OrderId = 11,
                            ProductId = 14,
                            Quantity = 2,
                            UnitPrice = 48000m
                        },
                        new
                        {
                            OrderItemId = 24,
                            LineTotal = 36000m,
                            OrderId = 11,
                            ProductId = 16,
                            Quantity = 2,
                            UnitPrice = 18000m
                        },
                        new
                        {
                            OrderItemId = 25,
                            LineTotal = 89000m,
                            OrderId = 12,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 89000m
                        },
                        new
                        {
                            OrderItemId = 26,
                            LineTotal = 169000m,
                            OrderId = 12,
                            ProductId = 12,
                            Quantity = 1,
                            UnitPrice = 169000m
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProductId");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8938501234561",
                            BrandId = 7,
                            CategoryId = 1,
                            CostPrice = 18000m,
                            IsActive = true,
                            Price = 25000m,
                            ProductName = "Rau cải bó xôi hữu cơ 300g",
                            StockQuantity = 50,
                            SupplierId = 1,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8938501234562",
                            BrandId = 7,
                            CategoryId = 1,
                            CostPrice = 24000m,
                            IsActive = true,
                            Price = 32000m,
                            ProductName = "Cà chua bi hữu cơ 500g",
                            StockQuantity = 40,
                            SupplierId = 1,
                            Unit = "hộp"
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8938501234563",
                            BrandId = 2,
                            CategoryId = 2,
                            CostPrice = 50000m,
                            IsActive = true,
                            Price = 65000m,
                            ProductName = "Yến mạch nguyên hạt Quaker 500g",
                            StockQuantity = 30,
                            SupplierId = 4,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8938501234564",
                            BrandId = 10,
                            CategoryId = 2,
                            CostPrice = 72000m,
                            IsActive = true,
                            Price = 95000m,
                            ProductName = "Hạt hạnh nhân rang Mỹ 250g",
                            StockQuantity = 25,
                            SupplierId = 4,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8938501234565",
                            BrandId = 5,
                            CategoryId = 3,
                            CostPrice = 60000m,
                            IsActive = true,
                            Price = 78000m,
                            ProductName = "Sữa hạnh nhân Alsafi 946ml",
                            StockQuantity = 35,
                            SupplierId = 5,
                            Unit = "hộp"
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8938501234566",
                            BrandId = 3,
                            CategoryId = 3,
                            CostPrice = 41000m,
                            IsActive = true,
                            Price = 55000m,
                            ProductName = "Sữa chua Hy Lạp không đường 500g",
                            StockQuantity = 20,
                            SupplierId = 5,
                            Unit = "hộp"
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8938501234567",
                            BrandId = 8,
                            CategoryId = 4,
                            CostPrice = 70000m,
                            IsActive = true,
                            Price = 89000m,
                            ProductName = "Ức gà tươi đông lạnh 1kg",
                            StockQuantity = 60,
                            SupplierId = 3,
                            Unit = "kg"
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8938501234568",
                            BrandId = 8,
                            CategoryId = 4,
                            CostPrice = 31000m,
                            IsActive = true,
                            Price = 42000m,
                            ProductName = "Cơm gạo lứt đóng hộp ăn liền 250g",
                            StockQuantity = 45,
                            SupplierId = 3,
                            Unit = "hộp"
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8938501234569",
                            BrandId = 6,
                            CategoryId = 5,
                            CostPrice = 110000m,
                            IsActive = true,
                            Price = 145000m,
                            ProductName = "Dầu oliu nguyên chất Extra Virgin 500ml",
                            StockQuantity = 20,
                            SupplierId = 6,
                            Unit = "chai"
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8938501234570",
                            BrandId = 11,
                            CategoryId = 5,
                            CostPrice = 88000m,
                            IsActive = true,
                            Price = 120000m,
                            ProductName = "Mật ong nguyên chất U Minh 500ml",
                            StockQuantity = 15,
                            SupplierId = 7,
                            Unit = "chai"
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8938501234571",
                            BrandId = 1,
                            CategoryId = 6,
                            CostPrice = 98000m,
                            IsActive = true,
                            Price = 129000m,
                            ProductName = "Táo Envy nhập khẩu 1kg",
                            StockQuantity = 30,
                            SupplierId = 2,
                            Unit = "kg"
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8938501234572",
                            BrandId = 1,
                            CategoryId = 7,
                            CostPrice = 135000m,
                            IsActive = true,
                            Price = 169000m,
                            ProductName = "Cá hồi phi lê Na Uy 300g",
                            StockQuantity = 22,
                            SupplierId = 8,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8938501234573",
                            BrandId = 7,
                            CategoryId = 8,
                            CostPrice = 40000m,
                            IsActive = true,
                            Price = 52000m,
                            ProductName = "Trứng gà ta hữu cơ hộp 10 quả",
                            StockQuantity = 70,
                            SupplierId = 9,
                            Unit = "hộp"
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8938501234574",
                            BrandId = 9,
                            CategoryId = 9,
                            CostPrice = 34000m,
                            IsActive = true,
                            Price = 48000m,
                            ProductName = "Trà hoa cúc thảo mộc 20 gói",
                            StockQuantity = 55,
                            SupplierId = 10,
                            Unit = "hộp"
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8938501234575",
                            BrandId = 8,
                            CategoryId = 10,
                            CostPrice = 28000m,
                            IsActive = true,
                            Price = 39000m,
                            ProductName = "Bánh quy yến mạch ít đường 200g",
                            StockQuantity = 65,
                            SupplierId = 11,
                            Unit = "gói"
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "8938501234576",
                            BrandId = 7,
                            CategoryId = 11,
                            CostPrice = 12000m,
                            IsActive = true,
                            Price = 18000m,
                            ProductName = "Đậu hũ non hữu cơ 300g",
                            StockQuantity = 80,
                            SupplierId = 12,
                            Unit = "hộp"
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "8938501234577",
                            BrandId = 12,
                            CategoryId = 12,
                            CostPrice = 100000m,
                            IsActive = true,
                            Price = 135000m,
                            ProductName = "Bột Spirulina tảo xoắn 100g",
                            StockQuantity = 18,
                            SupplierId = 11,
                            Unit = "hũ"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "ADMIN"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "MANAGER"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "CASHIER"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "Đà Lạt, Lâm Đồng",
                            Email = "lienhe@nongsandalat.vn",
                            PhoneNumber = "02633812345",
                            SupplierName = "Công ty TNHH Nông sản sạch Đà Lạt"
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "Quận 7, TP. Hồ Chí Minh",
                            Email = "sales@freshviet.vn",
                            PhoneNumber = "02838123456",
                            SupplierName = "Công ty CP Trái cây nhập khẩu Fresh Việt"
                        },
                        new
                        {
                            SupplierId = 3,
                            Address = "Bình Thạnh, TP. Hồ Chí Minh",
                            Email = "info@eatcleansg.vn",
                            PhoneNumber = "02838234567",
                            SupplierName = "Công ty TNHH Thực phẩm Eat Clean Sài Gòn"
                        },
                        new
                        {
                            SupplierId = 4,
                            Address = "Tân Bình, TP. Hồ Chí Minh",
                            Email = "order@ngucocmyviet.vn",
                            PhoneNumber = "02838345678",
                            SupplierName = "Công ty TNHH Ngũ cốc & Hạt Mỹ Việt"
                        },
                        new
                        {
                            SupplierId = 5,
                            Address = "Cầu Giấy, Hà Nội",
                            Email = "cskh@suaxanh.vn",
                            PhoneNumber = "02438456789",
                            SupplierName = "Công ty CP Sữa & Chế phẩm sữa Xanh"
                        },
                        new
                        {
                            SupplierId = 6,
                            Address = "Quận 1, TP. Hồ Chí Minh",
                            Email = "contact@diatrunghai.vn",
                            PhoneNumber = "02838567890",
                            SupplierName = "Công ty TNHH Dầu ăn Địa Trung Hải"
                        },
                        new
                        {
                            SupplierId = 7,
                            Address = "U Minh, Cà Mau",
                            Email = "htx@matonguminh.vn",
                            PhoneNumber = "02916678901",
                            SupplierName = "HTX Mật ong U Minh"
                        },
                        new
                        {
                            SupplierId = 8,
                            Address = "Phú Nhuận, TP. Hồ Chí Minh",
                            Email = "sales@haisannauy.vn",
                            PhoneNumber = "02838789012",
                            SupplierName = "Công ty TNHH Hải sản Na Uy Việt Nam"
                        },
                        new
                        {
                            SupplierId = 9,
                            Address = "Đức Hòa, Long An",
                            Email = "trangtrai@trungsachla.vn",
                            PhoneNumber = "02723890123",
                            SupplierName = "Trang trại Trứng sạch Long An"
                        },
                        new
                        {
                            SupplierId = 10,
                            Address = "Bảo Lộc, Lâm Đồng",
                            Email = "info@dalatgreen.vn",
                            PhoneNumber = "02633901234",
                            SupplierName = "Công ty TNHH Trà thảo mộc Dalat Green"
                        },
                        new
                        {
                            SupplierId = 11,
                            Address = "Thủ Đức, TP. Hồ Chí Minh",
                            Email = "ban-hang@snacklanhmanh.vn",
                            PhoneNumber = "02838012345",
                            SupplierName = "Công ty CP Bánh & Snack lành mạnh"
                        },
                        new
                        {
                            SupplierId = 12,
                            Address = "Gò Vấp, TP. Hồ Chí Minh",
                            Email = "lienhe@superfoodxanh.vn",
                            PhoneNumber = "02838123400",
                            SupplierName = "Công ty TNHH Đậu hũ & Superfood Xanh"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@healthymart.vn",
                            FullName = "Quản trị hệ thống",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000001",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 1, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manager01@healthymart.vn",
                            FullName = "Nguyễn Thị Quản Lý",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000002",
                            RoleId = 2,
                            Username = "manager01"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 1, 6, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "manager02@healthymart.vn",
                            FullName = "Trần Văn Điều Hành",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000003",
                            RoleId = 2,
                            Username = "manager02"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 2, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier01@healthymart.vn",
                            FullName = "Lê Thị Thu Ngân 1",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000004",
                            RoleId = 3,
                            Username = "cashier01"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2026, 2, 1, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier02@healthymart.vn",
                            FullName = "Phạm Văn Thu Ngân 2",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000005",
                            RoleId = 3,
                            Username = "cashier02"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2026, 2, 1, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier03@healthymart.vn",
                            FullName = "Hoàng Thị Thu Ngân 3",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000006",
                            RoleId = 3,
                            Username = "cashier03"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2026, 2, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier04@healthymart.vn",
                            FullName = "Võ Minh Thu Ngân 4",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000007",
                            RoleId = 3,
                            Username = "cashier04"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2026, 2, 10, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier05@healthymart.vn",
                            FullName = "Đặng Thị Thu Ngân 5",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000008",
                            RoleId = 3,
                            Username = "cashier05"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier06@healthymart.vn",
                            FullName = "Bùi Văn Thu Ngân 6",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000009",
                            RoleId = 3,
                            Username = "cashier06"
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2026, 3, 1, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier07@healthymart.vn",
                            FullName = "Ngô Thị Thu Ngân 7",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000010",
                            RoleId = 3,
                            Username = "cashier07"
                        },
                        new
                        {
                            UserId = 11,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier08@healthymart.vn",
                            FullName = "Đỗ Văn Thu Ngân 8",
                            IsActive = true,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000011",
                            RoleId = 3,
                            Username = "cashier08"
                        },
                        new
                        {
                            UserId = 12,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "cashier09@healthymart.vn",
                            FullName = "Lý Thị Thu Ngân 9",
                            IsActive = false,
                            PasswordHash = "$2b$11$Kce6ZlNDqAZeWGjWjezVDuvhT5YGuqyxFMjEc6g8Zx1VbYe0Rq7B.",
                            Phone = "0900000012",
                            RoleId = 3,
                            Username = "cashier09"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.User", "Cashier")
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cashier");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderItem", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.RefreshToken", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
